#!/bin/bash

# Copyright (C) 2017 Qualitance
# Licensed under the Apache License, Version 2.0.

# Fail script if any command fails.
set -e

# How to use this tool:
printUsage() {
  cat <<EOF
Usage: $(basename "${0}") [options] [\$platform]
Options:
  [-d | --debug]                            enables debug mode
  [-h | --help]                             shows this usage
  [-f | --fast]                             skip 'go get' commands
EOF
}

# Parse arguments.
fast=false
while [[ ${#} -ge 1 ]]; do
  # Debug mode
  if [[ "${1}" == "-d" || "${1}" == "--debug" ]]; then
    shift
    set -x
    continue
  fi
  # Help: display usage
  if [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
    shift
    printUsage
    exit 0
  fi
  # Fast: skip 'go get' commands
  if [[ "${1}" == "-f" || "${1}" == "--fast" ]]; then
    shift
    fast=true
    continue
  fi
  # Platform: linux / mac / windows
  if [[ -z ${platform} ]]; then
    platform=${1}
    shift
    continue
  fi
  # Unrecognized argument.
  printf "\e[1m\e[31mERROR: Unrecognized argument %s.\e[0m\e[0m\n" "${1}" >&2
  printUsage
  exit 1
done

if [[ ${platform} == "linux" ]]; then
  printf "%s\n" "Building for Linux..."
elif [[ ${platform} == "windows" ]]; then
  printf "%s\n" "Building for Windows..."
else
  if [[ ! -z ${platform} ]]; then
    printf "${RED}%s${STOP}\n" "ERROR: Unrecognized platform ${platform}."
    exit 2
  fi
  printf "%s\n" "Building..."
fi

script_path="$(dirname "$(readlink -f "${0}")")"
pushd "${script_path}" 1> /dev/null
{
GOPATH=$(git rev-parse --show-toplevel)
}
popd 1> /dev/null
GOBIN=${GOPATH}/bin

export GOPATH
export GOBIN

repositories=$(cat <<EOF
github.com/labstack/echo/...
github.com/leesper/couchdb-golang/...
EOF
)

pushd "${GOPATH}" 1> /dev/null
{
  if ! ${fast}; then
    pids=()
    for repository in ${repositories}; do
      go get -u ${repository} & pids+=(${!})
    done
    for pid in ${pids[@]}; do
      wait ${pid}
    done
    go clean -r
  fi

  if [[ ${platform} == "linux" ]]; then
    env GOOS=linux go build -v
  elif [[ ${platform} == "windows" ]]; then
    env GOOS=windows GOARCH=amd64 go build -v
  else
    go build -v
  fi
  result=${?}
}
popd 1> /dev/null

# shellcheck disable=SC2181
if [[ ${result} -eq 0 ]]; then
  printf "\nDone.\n"
else
  printf "\nErrors were encountered.\n"
  exit 3
fi

