#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
  [-o|--old]                   clean the old way with exporting GOPATH
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/spinner"

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  # [-o|--old]                   clean the old way with exporting GOPATH
  '-o'|'--old') old=true ;;
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1 ;;
  esac; shift
done

# Default arguments
[[ -z "${old+x}" ]] && old=false

# Export Go variables.
if ${old}; then
  . "${SCRIPT_PATH}/go-env"
fi

# Clean.
pushd "$(git rev-parse --show-toplevel)" 1> /dev/null
{
  start-spinner 'Cleaning...'
  go clean -r
  stop-spinner ${?}
}
popd 1> /dev/null
