#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Get script path and append it to PATH so other scripts are callable.
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
PATH="${PATH}:${SCRIPT_PATH}"

# Header
ARGUMENTS="\
"
. ${SCRIPT_PATH}/lib/header

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1 ;;
  esac; shift
done

if ! command -v godoc 1> /dev/null; then
  go get -u golang.org/x/tools/cmd/godoc
fi

# Get toplevel path.
pushd "${SCRIPT_PATH}" 1> /dev/null
{
  toplevel=$(git rev-parse --show-toplevel)
}
popd 1> /dev/null

pushd "${toplevel}" 1> /dev/null
{
  godoc -play -timestamps -v -http=:6060
}
popd 1> /dev/null

