#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/spinner"

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1 ;;
  esac; shift
done

if ! command -v godoc 1> /dev/null; then
  start_spinner 'Retrieving godoc...'
  go get -u golang.org/x/tools/cmd/godoc
  stop_spinner ${?}
fi

# Get toplevel path.
pushd "${SCRIPT_PATH}" 1> /dev/null
{
  toplevel=$(git rev-parse --show-toplevel)
}
popd 1> /dev/null

pushd "${toplevel}" 1> /dev/null
{
  start_spinner 'Generating documentation...'
  godoc -play -timestamps -v -http=:6060
  stop_spinner ${?}
}
popd 1> /dev/null

