#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/spinner"

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1
  esac; shift
done

# Export Go variables.
. "${SCRIPT_PATH}/go-env"

tmp="$(mktemp -u)"

start_spinner 'Formatting...'
pushd "${GOPATH}" 1> /dev/null
{
  files=$(find . -type f -name "*.go")
  for file in ${files}; do
    if [[ ${file} == *"src/github.com"* || \
          ${file} == *"src/golang.org"* || \
          ${file} == *"src/gopkg.in"* ]]; then
      continue
    fi
    gofmt -e -s "${file}" > "${tmp}"
    mv "${tmp}" "${file}"
  done
}
popd 1> /dev/null
stop_spinner 0
