#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

# Export Go variables.
pushd "${SCRIPT_PATH}" 1> /dev/null
{
  export GOPATH="$(git rev-parse --show-toplevel)"
  export GOBIN="${GOPATH}/bin"
}
popd 1> /dev/null
