#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/spinner"

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1
  esac; shift
done

# Install gometalinter if not installed.
export PATH="${PATH}:${GOPATH}/bin"
if ! command -v gometalinter 1> /dev/null; then
  go get -u github.com/alecthomas/gometalinter
  gometalinter --install
fi

# Export Go variables.
. "${SCRIPT_PATH}/go-env"

# Lint recursively.
pushd "${GOPATH}" 1> /dev/null
{
  start-spinner 'Linting...'
  directories=$(find src -mindepth 1 -maxdepth 1 -type d | sort -V)
  files=$(find . -maxdepth 1 -type f -name "*.go")
  recursive_directories=
  for directory in ${directories}; do
    if [[ ${directory} == *"src/github.com"* || \
          ${directory} == *"src/golang.org"* || \
          ${directory} == *"src/gopkg.in"* ]]; then
      continue
    fi
    recursive_directories+="${directory}/... "
  done
  gometalinter ${recursive_directories} ${files} | sort -V
  stop-spinner ${?}
}
popd 1> /dev/null
