#!/bin/bash

# Copyright (C) 2017-2018 Qualitance, andrei.pavel@qualitance.com
# Licensed under the MIT License

# Get script path and append it to PATH so other scripts are callable.
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
PATH="${PATH}:${SCRIPT_PATH}"

# Header
ARGUMENTS="\
"
. ${SCRIPT_PATH}/lib/header

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  *)
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1
  esac; shift
done

# Install gometalinter if not installed.
export PATH="${PATH}:${GOPATH}/bin"
if ! command -v gometalinter 1> /dev/null; then
  go get -u github.com/alecthomas/gometalinter
  gometalinter --install
fi

# Get toplevel path.
pushd "${SCRIPT_PATH}" 1> /dev/null
{
  GOPATH=$(git rev-parse --show-toplevel)
}
popd 1> /dev/null

# Export Go variables.
GOBIN=${GOPATH}/bin
export GOPATH
export GOBIN

# Lint recursively.
pushd "${GOPATH}" 1> /dev/null
{
  directories=$(find src -mindepth 1 -maxdepth 1 -type d)
  files=$(find . -maxdepth 1 -type f -name "*.go")
  recursive_directories=
  for directory in ${directories}; do
    if [[ ${directory} == *"src/github.com"* || \
          ${directory} == *"src/golang.org"* || \
          ${directory} == *"src/gopkg.in"* ]]; then
      continue
    fi
    recursive_directories+="${directory}/... "
  done
  gometalinter ${recursive_directories} ${files} | sort -V
}
popd 1> /dev/null

