#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
  \$hosts                       hosts to deploy to
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/utils"

# Get toplevel path.
pushd "${SCRIPT_PATH}" 1> /dev/null
{
  toplevel=$(git rev-parse --show-toplevel)
}
popd 1> /dev/null

pushd "${toplevel}" 1> /dev/null
{
  if (( ${#} == 0 )); then
    # Locally
    docker-compose logs -f --tail=128
  else
    # Remotely
    root_directory="$(basename "${toplevel}")"
    for host in "${@}"; do
      ssh "${host}" "\
        cd \"${root_directory}\"
        scripts/monitor $(additional)
      "
    done
  fi
}
popd 1> /dev/null
