#!/bin/bash

# Copyright (C) 2017-2018 Qualitance, andrei.pavel@qualitance.com
# Licensed under the MIT License

# Get script path and append it to PATH so other scripts are callable.
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
PATH="${PATH}:${SCRIPT_PATH}"

# Header
ARGUMENTS="\
"
. ${SCRIPT_PATH}/lib/header

rsync --verbose --progress --human-readable --compress --archive --hard-links --one-file-system --acls --xattrs --update --delete ${@}
